version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4-stretch
    working_directory: /go/src/github.com/nshttpd/mikrotik-exporter
    branches:
      - master
      - /^nshttpd.*/
    steps:
      - checkout
      - run: make deploy