devices:
  - name: test1
    address: 192.168.1.1
    user: foo
    password: bar
  - name: test2
    address: 192.168.2.1
    user: test
    password: 123

features:
  bgp: true
  conntrack: true
  dhcp: true
  dhcpv6: true
  dhcpl: true
  routes: true
  pools: true
  optics: true
  wlansta: true
  wlanif: true
  ipsec: true
  lte: true
  netwatch: true
